### PR TITLE
Update privilege_elevation_all.yaml

### PR DESCRIPTION
**Pull request by SkylerGodfrey**
Updated PrivilegeElevation to UserElevation.

### CODE REVIEW

**Comment by SkylerGodfrey** [comment]
Working with Andrew Pantelis, after reviewing the existing unified log for privilege elevation we found after running a log stream, this is actually looking for UserElevation not PrivilegeElevation.

**Comment by txhaflaire** [comment]
Hi Skyler,

Thanks for putting this in - we are going to quickly review this as my latest testing with Jamf Connect 2.39/40 are using `PrivilegeElevation` as category

**Comment by txhaflaire** [comment]
@SkylerGodfrey After further review, only a specific version of Jamf Connect 2.36 had this `UserElevation` category during that version. all of the previous and more current versions use `PrivilegeElevation`

**Comment by txhaflaire** [comment]
Closing this pull request as the most recent versions do use the category `PrivilegeElevation`.

**Pull request closed without merging**
